# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20171007_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created', '-pk'), 'verbose_name': 'новость', 'verbose_name_plural': 'новости'},
        ),
    ]
