# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 18:25
from __future__ import unicode_literals

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20171007_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created', '-pk'), 'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_content',
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default='_autofixture/200x300.png', upload_to='news/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='large',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
