# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 13:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название секции')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Содержимое секции')),
                ('enabled', models.BooleanField(verbose_name='Секция активна?')),
            ],
            options={
                'verbose_name': 'Секция главной страницы на главной',
                'verbose_name_plural': 'Секции главной страницы на главной',
            },
        ),
    ]
