# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='template_name',
            field=models.CharField(default='sections/section.html', max_length=50),
        ),
    ]
