# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-27 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_api', '0002_auto_20170726_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-article']},
        ),
    ]
